//
// !!! AUTOGENERATED FILE. DO NOT HAND-EDIT !!!
//

namespace omaha {

// PROXY_CLSID_IS_MACHINE = {14315884-63EC-4D51-A167-68757AC714B8}
const GUID kProxyClsidIsMachineGuid =
    {0x14315884, 0x63EC, 0x4D51, {0xA1, 0x67, 0x68, 0x75, 0x7A, 0xC7, 0x14, 0xB8}};

// PROXY_CLSID_IS_USER = {A4256D74-11E9-4CCC-8528-2C751EEC3440}
const GUID kProxyClsidIsUserGuid =
    {0xA4256D74, 0x11E9, 0x4CCC, {0x85, 0x28, 0x2C, 0x75, 0x1E, 0xEC, 0x34, 0x40}};

}  // namespace omaha
